In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('data.csv')

Q1. Pandas version
What's the version of Pandas that you installed?


In [2]:
pd.__version__

'2.2.3'

Q2. Records count
How many records are in the dataset?

- 12
- 1000
- 2160 X
- 12160

In [3]:
df.shape[0]

2160

Q3. Laptop brands
How many laptop brands are presented in the dataset?

- 12
- 27 X
- 28
- 2160

In [4]:
df['Brand'].nunique()

27

Q4. Missing values
How many columns in the dataset have missing values?

- 0
- 1
- 2
- 3 X

In [6]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

- 869
- 3691
- 3849
- 3936 X

In [7]:
df[df['Brand'] == 'Dell']['Final Price'].max()

np.float64(3936.0)

Q6. Median value of Screen
1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

- Yes X
- No

In [27]:
median_with_nulls = df['Screen'].median()
median_with_nulls

np.float64(15.6)

In [30]:
df['Screen'].value_counts()

Screen
15.60    1009
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.40      19
13.50      19
11.60      16
14.20      14
12.30      13
14.10      11
13.60      11
16.20      10
15.30       8
10.50       7
12.40       6
14.40       6
15.40       5
12.00       4
18.00       3
14.50       3
13.90       2
12.50       1
10.95       1
10.10       1
Name: count, dtype: int64

In [35]:
df_no_null = df.fillna(15.60).__deepcopy__(True)

In [34]:
median_no_nulls = df_no_null['Screen'].median()
median_no_nulls

np.float64(15.6)

In [36]:
assert median_with_nulls == median_no_nulls

Q7. Sum of weights
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

- 0.43
- 45.29
- 45.58
- 91.30 X

In [42]:
X = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']].to_numpy(copy=True)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [46]:
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [48]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [50]:
y = np.array([1100,1300,800,900,1000,1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [52]:
w = XTX_inv.dot(X.T).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [53]:
w.sum()

np.float64(91.2998806299555)